config/routes.rb
RottenMangoes::Application.routes.draw do

  root to: 'movies#index'

  get 'search' => 'search#index'

  # get 'reviews/new'

  # get 'reviews/create'

  # get 'sessions/new'

  # post 'sessions/create'

  # get 'users/new'

  # get 'users/create'

  # delete 'session/:id' => "session#destroy"

  resources :movies do
    resources :reviews, only: [:new, :create]
  end

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]

  namespace :admin do
    resources :users
  end

end

app/models/movie.rb
class Movie < ActiveRecord::Base

  has_many :reviews

  validates :title, presence: true
  validates :director, presence: true
  validates :runtime_in_minutes, numericality: {only_integer: true}
  validates :description, presence: true
  validates :release_date, presence: true
  validate :release_date_is_in_the_past
  validate :must_have_image

  mount_uploader :image, ImageUploader

  def review_average
    if reviews.sum(:rating_out_of_ten) == 0
      "No reviews yet"
    else reviews.sum(:rating_out_of_ten)/reviews.size
    end
  end

  protected

  def release_date_is_in_the_past
    if release_date.present?
      errors.add(:release_date, "should be in the past") if release_date > Date.today
    end
  end

  def must_have_image
    if image.blank? && poster_image_url.blank?
      errors.add(:image, "Please add image either by URL or uploader")
    end
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie

  validates :user, presence: true
  validates :movie, presence: true
  validates :text, presence: true
  validates :rating_out_of_ten, numericality: { greater_than_or_equal_to: 1 }
  validates :rating_out_of_ten, numericality: { less_than_or_equal_to: 10 }
  validates :rating_out_of_ten, numericality: { only_integer: true }
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :reviews, dependent: :destroy

  has_secure_password

  validates :email, presence: true
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :password, length: { in: 6..20}, on: :create

  def full_name
    "#{firstname} #{lastname}"
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_filter :restrict_admin_access


  def index
    @users = User.order("firstname").page(params[:page]).per(10)
  end

  def destroy
    @user = User.find(params[:id])
    UserMailer.deleted_user_email(@user).deliver

    @user.destroy
    redirect_to admin_users_path, "Deleted"
  end

  protected

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def restrict_access
    if !current_user
      flash[:alert] = "Please log in."
      redirect_to '/movies'
    end
  end

  def restrict_admin_access
    if current_user && !current_user.roles.include?("admin")
      flash[:alert] = "You aren't an admin, sorry."
      redirect_to '/movies'
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully"
    else
      render :new
    end
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update_attributes(movie_params)
      redirect_to movies_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  protected

  def movie_params
    params.require(:movie).permit(
      :title, :release_date, :director, :runtime_in_minutes, :description, :image, :poster_image_url
      )
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :restrict_access
  before_filter :load_movie

  def new
    @review = @movie.reviews.build
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Successfully created review"
    else
      render :new
    end
  end

  protected

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    title_or_director = params[:title_or_director]
    runtime = params[:runtime_in_minutes].to_i

    query = "(title like '#{params[:title_or_director]}%' or director like '#{params[:title_or_director]}%')"

    query += " and runtime_in_minutes < 90" if runtime < 90
    query += " and runtime_in_minutes >= 90 and runtime_in_minutes <= 120" if runtime >= 90 && runtime <= 120
    query += " and runtime_in_minutes > 120" if runtime > 120

    @movies = Movie.where(query)

  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user= User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}"
    else
      flash.now[:alert] = "Log in was unsuccessful"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "Bye for now!"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user= User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}"
    else
      flash.now[:alert] = "Log in was unsuccessful"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "Bye for now!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to movies_path, notice: "Welcome aboard, Mr.#{@user.lastname}"
    else
      render :new
    end
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end

  def admin?
    User.find(session[:user_id]).admin
  end

  def admin_redirect
    redirect_to admin_users_path, notice: "User created" if admin?
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<strong><%= link_to "Back to movies", movies_path %></strong>
<h1>Current Users</h1>
<%= paginate @users %>

<% @users.each do |user| %>
  <p><strong>Name:</strong> <%= user.full_name %></p>
  <p><strong>Email:</strong> <%= user.email %></p>
  <%= link_to "Remove this user from database", admin_user_path(user), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-primary"%>
  <hr>
<% end %>

app/views/layouts/_admin_footer.html.erb
<% if current_user && current_user.roles && current_user.roles.include?("admin") %>
  <div>
    <%= link_to "Admin", admin_users_path %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>

  <small>
    <% if current_user %>
      Signed in as <strong><%= current_user.full_name %></strong>. (Not you? <%= link_to "Log out", "/sessions/#{current_user.id}", method: :delete %>. Or head into the <%= link_to "Admin area", "/admin/users" %>).
    <% else %>
      <%= link_to "Log in", new_session_path %> | <%= link_to "Sign up", new_user_path %>
    <% end %>
  </small>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rotten Mangoes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value) %>
  <% end %>
<%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie, :html => {:multipart => true} do |t| %>
  <% if @movie.errors.any? %>
    <div> 
      <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being accepted:
      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="fancy">
    <%= t.label :title %><br>
    <%= t.text_field :title %>
  </div>
  <br>
  <div>
    <%= t.label :release_date %><br>
    <%= t.date_field :release_date %>
  </div>
  <br>
  <div>
    <%= t.label :director %><br>
    <%= t.text_field :director %>
  </div>
  <br>
  <div>
    <%= t.label :runtime_in_minutes %><br>
    <%= t.number_field :runtime_in_minutes %>
  </div>
  <br>
  <div>
    <%= t.label :poster_image_url %><br>
    <%= t.text_field :poster_image_url %>
  </div>
  <br>
  <div>
    <%= t.file_field :image %>
  </div>
  <br>
  <div>
    <%= t.label :description %><br>
    <%= t.text_area :description %>
  </div>
  <br>
  <div>
    <%= t.submit "Submit" %> 
  </div>
<% end %>
<hr>

app/views/movies/_movie.html.erb
<% @movies.each do |movie| %>
  <%= image_tag movie.image_url.to_s, class: "image_edit" %>
  <%= link_to image_tag(movie.poster_image_url), movie_path(movie), class: "image_edit" %>
  <h2><%= link_to movie.title, movie_path(movie) %></h2>
  <h3><%= formatted_date(movie.release_date) %></h3>
  <h4>Director: <%= movie.director %> | Length: <%= movie.runtime_in_minutes %> minutes</h4>
  <p><%= movie.description %> </p>
  <%= movie.review_average %>/10
  <hr>
<% end %>

app/views/movies/_search.html.erb
<%= form_tag("/search", method: "get") do %>
  <%= label_tag(:title_or_director, "Search by title or director:") %>
  <br>
  <%= text_field_tag :title_or_director %>
  <br>
  <br>
  <%= label_tag(:runtime_in_minutes, "Runtime:") %>
  <br>
  <select name="runtime_in_minutes">
    <option value="89">Under 90 minutes</option>
    <option value="90">Between 90 and 120 minutes</option>
    <option value="121">Over 120 minutes</option>
  </select>
  <br>
  <br>
  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>

app/views/movies/edit.html.erb
<%= link_to "Back to this movie", movie_path(@movie) %>

<h2>Edit this movie.</h2>

<%= render 'form' %>

app/views/movies/index.html.erb
<h1>Rotten Mangoes</h1>

<div id="container">
<%= link_to "Submit a movie!", new_movie_path %>
<hr>

<h3>Search For A Movie</h3>

<%= render 'search' %>

<hr>

<%= render 'movie' %>
</div>

app/views/movies/new.html.erb
<%= link_to "Back to all the movies", movies_path %>

<h2>Submit a movie</h2>

 <%= render 'form' %>

app/views/movies/show.html.erb
<%= link_to "Back to all them movies, dawg", movies_path %><br/>
<hr>

<%= image_tag @movie.image_url.to_s %>
<%= link_to image_tag(@movie.poster_image_url), movie_path(@movie) %>
<h2><%= @movie.title %> (<%= link_to "Edit", edit_movie_path(@movie) %>, <%= link_to "Delete", movie_path(@movie), method: :delete, confirm: "You sure you want to do that?" %>)</h2>
<h3><%= formatted_date(@movie.release_date) %></h3>
<h4>Director: <%= @movie.director %> | Length: <%= @movie.runtime_in_minutes %> minutes</h4>
<p><%= @movie.description %></p>

<hr>

<h3>Reviews of <em><%= @movie.title %></em></h3>
<% if current_user %>
  <% @movie.reviews.each do |review| %>
    <p><%= review.text %></p>
    <p><%= review.rating_out_of_ten %>/10</p>
    <small>- <%= review.user.firstname %></small><br/>
  <% end %>
  <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to see reviews and add your own.</p> 
<% end %>
<hr>

app/views/reviews/new.html.erb
<%= link_to "Back to movie", movie_path(@movie) %><br/>

<h2>Write a review of <em><%= @movie.title %></em>.</h2>

  <%= form_for([@movie, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div>
      <%= pluralize(@review.errors.count, "error") %> is preventing the review from being saved:
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

      <div>
        <%= f.label :text %><br>
        <%= f.text_area "text" %>
      </div>
      <div>
        <%= f.label :rating_out_of_ten %><br>
        <%= f.number_field :rating_out_of_ten %>
      </div>
      <div><%= f.submit "Submit" %></div>
    <% end %>

app/views/search/index.html.erb
<h1>Found what you were looking for?</h1>
<%= link_to "Back to Main", movies_path %>
<br>
<% @movies.each do |movie| %>
  <%= link_to image_tag(movie.poster_image_url), movie_path(movie) %>
  
  <h2><%= link_to movie.title, movie_path(movie) %></h2>
  
  <h3><%= formatted_date(movie.release_date) %></h3>
  
  <h4>Director: <%= movie.director %> | Length: <%= movie.runtime_in_minutes %> minutes</h4>
  
  <p><%= movie.description %></p>
  <hr>
<% end %>

app/views/session/new.html.erb
<h1>Log in!</h1>
<%= form_tag session_path do %>
  <div>
    <%= label_tag :email %><br/>
    <%= text_field_tag :email %>
  </div>
  <div>
    <%= label_tag :password %> <br/>
    <%= password_field_tag :password %>
  </div>
  <br>
  <div><%= submit_tag "Log in!" %></div>
<% end %>

app/views/users/new.html.erb
<h1>Sign up!</h1>
<%= form_for @user do |t| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented your sign up:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= t.label "email" %><br>
    <%= t.text_field "email" %>
  </div>
  <br>
  <div>
    <%= t.label "firstname", "First Name" %><br>
    <%= t.text_field "firstname" %>
  </div>
  <br>
  <div>
    <%= t.label "lastname", "Last Name" %><br>
    <%= t.text_field "lastname" %>
  </div>
  <br>
  <div>
    <%= t.label "password" %><br>
    <%= t.password_field "password" %>
  </div>
  <br>
  <div>
    <%= t.label "password_confirmation" %><br>
    <%= t.password_field "password_confirmation" %>
  </div>
  <br>
  <div><%= t.submit "Submit" %></div>

<% end %>